=head1 NAME

Mecom - A Perl program for protein contact interfaces evolutive analysis

=head1 VERSION

Version 1.12

=head1 SYNOPSIS
=head1 OPTION SUMMARY
=head1 OUTPUT
=head1 DATA PREPARATION
=head1 CONTACT FILE
=head1 GENETIC CODES
=head1 MSA VALID FORMATS
=head1 SINGLE SUBUNIT ANALYSIS EXAMPLES
=head1 MULTIPLE SUBUNITS ANALYSIS EXAMPLE
=head1 OTHER EXAMPLES
=head1 AUTHOR - Hector Valverde

Hector Valverde, C<< <hvalverde@uma.es> >>

=head1 CONTRIBUTORS

Juan Carlos Aledo, C<< <caledo@uma.es> >>

=head1 OR CONTACT WITH US AT

    http://mecom.hval.es/contact

=head1 BUGS

Please report any bugs or feature requests to C<bug-Mecom at rt.cpan.org>, or through
the web interface at L<http://rt.cpan.org/NoAuth/ReportBug.html?Queue=Mecom>.
I will be notified, and then you'll automatically be notified of progress on your bug as I make changes.

=head1 SUPPORT

Further information about this project is available at:

    http://mecom.hval.es/

You can find this docs for this module with the UNIX man command.

    man Mecom


=head1 LICENSE AND COPYRIGHT

Copyright 2013 Hector Valverde and Juan Carlos Aledo.

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.

=cut

